### ISSUE TITLE
pa11y-ci ends with an npm error after the displaying the results

### ISSUE THREAD

**Issue by rkrjain** [pa11y/pa11y-ci#83] opened 2019-06-11 08:15 UTC
I have spent hours trying to overcome this issue where the pa11y-ci ends with an error. It throws out the errors and ends with this error below

```

   (#mat-input-1)

   <input _ngcontent-fgs-c4="" class="mat-input-element
   mat-form-field-autofill-control cdk-text-field-autofill-monitored
   ng-untouched ng-pristine ng-invalid" formcontrolname="password" matinput=""
   onpaste="return false" placeholder="Password" type="pas...

✘ 2/3 URLs passed
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @xxxxxxxxxxxx@0.0.0 a11y-report: `pa11y-ci`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @xxxxxxxxxxxx@0.0.0 a11y-report script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\M1030316\AppData\Roaming\npm-cache\_logs\2019-06-11T08_10_41_881Z-debug.log


```

Need quick help in fixing this problem; I am blocked because of this.

this is my **.pa11yci**

```json
{
  "defaults": {
    "ignore": ["notice"],
    "standard": "WCAG2A"
  },
  "urls": [
    "http://localhost:4200/not-found",
    "http://localhost:4200/not-authorized",
    "http://localhost:4200/admin"
  ]
}
```
I am just running "pa11y-ci" from the terminal.

**Comment by tmasrat** [comment] 2019-06-14 17:42
@rgjain what version of node do you have?

**Comment by braican** [comment] 2020-01-14 02:06
NPM is exiting with an error because there's an accessibility error in your tests. As far as I can tell, this is the expected behavior: by default the pa11y script returns an exit code of 2 if there is an accessibility error, which NPM interprets as an error with the script that was being run.

Presumably this was done this way so that when the tests were run in CI the NPM script itself would fail, which would kill the process and prevent inaccessible code or features from being pushed to whatever environment the CI is hooked up to.

**Comment by josebolos** [comment] 2021-02-08 15:45
Thanks for creating this issue. It looks like this is now fixed, feel free to reopen the issue if not.

**Closed by josebolos** 2021-02-08 15:45 UTC
