### ISSUE TITLE
Show errors even when under threshold

### ISSUE THREAD

**Issue by pinglinh** [pa11y/pa11y-ci#70] opened 2018-11-06 15:23 UTC
I noticed that when errors shown are under the threshold specified, the errors no longer show. Is it possible to make an enhancement to this to add the option of showing these errors anyways? I think it will be good in terms of trying to improve and get rid of these errors before pushing the code to build in our CI pipelines.

**Comment by 42tte** [comment] 2020-02-16 22:59
Duplicate of #54

**Comment by dapenguin** [comment] 2020-06-02 12:48
Had a similar issue last week, but realised it was down to how I was configuring `pa11y`. I was setting `threshold` inside my `.pa11yci.json` file, and so when the errors were below that threshold it wouldn't output what the errors were. However, if I removed the `threshold` from there and used the `-T` flag in the CLI, that would still report the errors even if they fell below the threshold.

Don't know if that helps at all.

**Comment by I-Valchev** [comment] 2021-01-08 15:47
@42tte hey, I'm bumping into the same issue. It appears the `-T` or `--threshold` don't work at all?

**Comment by 42tte** [comment] 2021-01-08 16:48
@I-Valchev 

`-T`/`--threshold` are Pa11y CLI options https://github.com/pa11y/pa11y#command-line-interface not Pa11y-CI CLI options https://github.com/pa11y/pa11y-ci#usage

Have a look at https://github.com/pa11y/pa11y-ci#default-configuration for how to set it up with Pa11y-CI config

**Comment by 42tte** [comment] 2021-01-08 22:31
@I-Valchev Try `pa11y-ci --threshold 83 --config tests/a11y/pa11yci.json`

**Comment by I-Valchev** [comment] 2021-01-11 08:36
hi @42tte ,

You asked if I try this: `pa11y-ci --threshold 83 --config tests/a11y/pa11yci.json`

But unfortunately it doesn't work. I much prefer an option in the command line rather than the config, because that way I can use the config for CI (where I don't want it to fail for the number of existing issues, but I'd like it to fail if new ones come up) wheres I want to use that same config locally to look at all the issues (so no threshold).

Is that not possible at the moment? Thanks!

**Comment by danyalaytekin** [comment] 2023-10-11 21:36
Thanks all, and for the pointer to #54 @42tte. Let's track this there.

**Closed by danyalaytekin** 2023-10-11 21:36 UTC
